blank_issues_enabled: false
contact_links:
  - name: Soporte General
    url: https://github.com/MacRimi/ProxMenux/discussions
    about: Si tu solicitud no es un bug ni un feature, usa las discusiones.
